indent = 2
include-doc-id = true
use-ctags = "never"

[tags]
verbatim = [
  "pre",
  "latex-image-preamble",
  "latex-image",
  "latex-preamble",
  "slate",
  "sage",
  "sageplot",
  "asymptote",
  "macros",
  "input",
  "output",
  "tests",
  "prompt",
  "pre",
  "pg-code",
  "tikzpicture",
  "tikz",
]
block = ["ul", "ol", "dl", "chapter", "section", "me", "men", "md", "mdn", "cd"]
block-no-indent = []
inline = [
  "em",
  "q",
  "sq",
  "c",
  "pubtitle",
  "articletitle",
  "abbr",
  "init",
  "acro",
  "delete",
  "insert",
  "stale",
  "fn",
  "m",
  "taxon",
  "email",
  "url",
  "xref",
  "idx",
  "notation",
  "foreign",
  "term",
  "alert",
  "angles",
  "dblbrackets",
  "tag",
  "attr",
  "mdash",
  "kbd",
  "ellipsis",
  "registered",
  "permille",
  "section-mark",
  "trademark",
  "copyright",
  "pilcrow",
  "midpoint",
  "swungdash",
  "times",
  "solidus",
  "obelus",
  "plusminus",
  "degree",
  "prime",
  "dblprime",
  "fillin",
  "area",
]
inline-empty = ["var", "pretext", "eval"]
