name: Generate GitHub pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/python-app.yml
    secrets: inherit
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download pages artifact
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs
      - id: deployment
        uses: actions/deploy-pages@v4

