# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: "3.12"
        cache: true
        cache-dependency-path: |
          ./pdm.lock
      # You are now able to use PDM in your workflow
    - name: Install dependencies
      run: pdm install
    - name: Lint and error if needed
      run: pdm run lint-diff
    - name: Run tests
      run: pdm run test
    - name: Build
      run: pdm build
    - name: Generate docs
      run: pdm doc
    - name: Upload docs artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
