name: Release to PyPi

on:
  push:
    tags: ["*"]

jobs:
  build:
    uses: ./.github/workflows/python-app.yml
    secrets: inherit
  release:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/ptx-formatter/
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
          run-id: ${{ needs.build.outputs.runId }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
